### ISSUE TITLE
Let the user select the Team if he/she is part of multiple teams

### ISSUE THREAD

**Issue by pnull** [jfahrenkrug/WWDC-Downloader#18]
```

../lib/ruby/gems/2.0.0/gems/mechanize-2.7.1/lib/mechanize/http/agent.rb:940:in `response_read': Content-Length (2423) does not match response body length (2421) (Mechanize::ResponseReadError) (Mechanize::ResponseReadError)
	from ../lib/ruby/gems/2.0.0/gems/mechanize-2.7.1/lib/mechanize/http/agent.rb:260:in `block in fetch'
	from ../lib/ruby/2.0.0/net/http.rb:1413:in `block (2 levels) in transport_request'
	from ../lib/ruby/2.0.0/net/http/response.rb:162:in `reading_body'
	from ../lib/ruby/2.0.0/net/http.rb:1412:in `block in transport_request'
	from ../lib/ruby/2.0.0/net/http.rb:1403:in `catch'
	from ../lib/ruby/2.0.0/net/http.rb:1403:in `transport_request'
	from ../lib/ruby/2.0.0/net/http.rb:1376:in `request'
	from ../lib/ruby/gems/2.0.0/gems/net-http-persistent-2.8/lib/net/http/persistent.rb:931:in `request'
	from ../lib/ruby/gems/2.0.0/gems/mechanize-2.7.1/lib/mechanize/http/agent.rb:257:in `fetch'
	from ../lib/ruby/gems/2.0.0/gems/mechanize-2.7.1/lib/mechanize/http/agent.rb:974:in `response_redirect'
	from ../lib/ruby/gems/2.0.0/gems/mechanize-2.7.1/lib/mechanize/http/agent.rb:298:in `fetch'
	from ../lib/ruby/gems/2.0.0/gems/mechanize-2.7.1/lib/mechanize/http/agent.rb:974:in `response_redirect'
	from ../lib/ruby/gems/2.0.0/gems/mechanize-2.7.1/lib/mechanize/http/agent.rb:298:in `fetch'
	from ../lib/ruby/gems/2.0.0/gems/mechanize-2.7.1/lib/mechanize/http/agent.rb:869:in `response_follow_meta_refresh'
	from ../lib/ruby/gems/2.0.0/gems/mechanize-2.7.1/lib/mechanize/http/agent.rb:282:in `fetch'
	from ../lib/ruby/gems/2.0.0/gems/mechanize-2.7.1/lib/mechanize.rb:1272:in `post_form'
	from ../lib/ruby/gems/2.0.0/gems/mechanize-2.7.1/lib/mechanize.rb:539:in `submit'
	from ../lib/ruby/gems/2.0.0/gems/mechanize-2.7.1/lib/mechanize/form.rb:223:in `submit'
	from ../lib/ruby/gems/2.0.0/gems/mechanize-2.7.1/lib/mechanize/form.rb:229:in `click_button'
	from ../lib/ruby/gems/2.0.0/gems/wwdcdownloader-20.13.5/lib/wwdcdownloader.rb:70:in `block in login'
	from ../lib/ruby/gems/2.0.0/gems/mechanize-2.7.1/lib/mechanize.rb:433:in `get'
	from ../lib/ruby/gems/2.0.0/gems/wwdcdownloader-20.13.5/lib/wwdcdownloader.rb:66:in `login'
	from ../lib/ruby/gems/2.0.0/gems/wwdcdownloader-20.13.5/lib/wwdcdownloader.rb:271:in `run!'
	from .//.rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/gems/wwdcdownloader-20.13.5/bin/wwdcdownloader:5:in `<main>'
```

**Comment by jfahrenkrug** [comment]
For 2015, no login is necessary anymore, so I'm closing it.
